# Generated by Django 6.0.6 on 2026-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_offerredemption_usage_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='offerredemption',
            name='offer_redemption_user_offer_idx',
        ),
        migrations.AddIndex(
            model_name='offerredemption',
            index=models.Index(
                fields=['user', 'offer', 'redeemed_at'],
                name='offer_redemp_user_offer_idx',
            ),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage_bill', 'Percentage off entire bill'), ('item', 'Item or service discount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='usage_limit_type',
            field=models.CharField(choices=[('one_time', 'One time only'), ('once_per_week', 'Once per week'), ('once_per_month', 'Once per month'), ('n_times_per_week', 'N times per week'), ('n_times_per_month', 'N times per month'), ('n_times_total', 'N times total')], max_length=20),
        ),
    ]
